# Generated by Django 5.2.6 on 2025-09-19 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('idHilo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Hilo')),
                ('tituloHilo', models.CharField(max_length=25, verbose_name='Titulo del Hilo')),
                ('cuerpoHilo', models.CharField(max_length=255, verbose_name='Cuerpo del Hilo')),
                ('imagenHilo', models.ImageField(null=True, upload_to='car')),
                ('puntosHilo', models.IntegerField(verbose_name='Puntuacion Hilo')),
                ('autorHilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Comentario')),
                ('cuerpoComentario', models.CharField(max_length=150, verbose_name='Cuerpo del Comentario')),
                ('autorComentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('padreComentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.hilo')),
            ],
        ),
    ]
